<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="LoginService" targetNamespace="http://bs5lnd.org/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://bs5lnd.org/wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://bs5lnd.org/wsdl" schemaLocation="LoginService_schema1.xsd"></import>
</schema>
  </wsdl:types>
  <wsdl:message name="validateLogin">
    <wsdl:part name="parameters" element="tns:validateLogin">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="validateLoginResponse">
    <wsdl:part name="parameters" element="tns:validateLoginResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="activateUserResponse">
    <wsdl:part name="parameters" element="tns:activateUserResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="activateUser">
    <wsdl:part name="parameters" element="tns:activateUser">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="LoginServiceEndpoint">
    <wsdl:operation name="validateLogin">
      <wsdl:input name="validateLogin" message="tns:validateLogin">
    </wsdl:input>
      <wsdl:output name="validateLoginResponse" message="tns:validateLoginResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="activateUser">
      <wsdl:input name="activateUser" message="tns:activateUser">
    </wsdl:input>
      <wsdl:output name="activateUserResponse" message="tns:activateUserResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LoginServiceSoapBinding" type="tns:LoginServiceEndpoint">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="validateLogin">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="validateLogin">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="validateLoginResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="activateUser">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="activateUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="activateUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LoginService">
    <wsdl:port name="LoginServicePort" binding="tns:LoginServiceSoapBinding">
      <soap:address location="http://localhost:9090/LoginServicePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
