
package org.bs5lnd.webservice.endpoints.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * Wed Jun 25 12:37:51 CST 2014
 * Generated source version: 2.7.7.redhat-1
 */

@XmlRootElement(name = "validateLoginResponse", namespace = "http://bs5lnd.org/wsdl")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateLoginResponse", namespace = "http://bs5lnd.org/wsdl")

public class ValidateLoginResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

